import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Box, Container } from "@mui/material";

import Navbar from "@/components/Navbar";
import HomeHero from "@/components/HomeHero";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Estuary</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Work+Sans&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Box
        sx={{
          // border: "2px solid red",
          height: "100vh",
          backgroundColor: "#0C0B0B",
          position: "relative",
        }}
      >
        <Container
          maxWidth="lg"
          // sx={{ border: "2px solid blue", height: "100vh" }}
        >
          {/* <div className=" h-96 bg-neon rounded-xl w-96 absolute top-0 left-0 blur-custom  border-2 border-stone-200"></div> */}

          <Navbar />
          <HomeHero />

          <div className="   h-80 bg-emerald rounded-xl w-56 absolute top-50 right-0 -mr-24 blur-custom  opacity-100"></div>
          <div className="  h-80  bg-neon rounded-xl w-56 absolute bottom-0 left-0 -mr-24 blur-custom  opacity-100"></div>

          {/* <div className=" h-full   w-blur rounded-xl absolute top-0 right-0  backdrop-blur-custom   "></div> */}
        </Container>
      </Box>
    </>
  );
}
